### PR TITLE
Homogenize indentation accross m4 files

### PR DESCRIPTION
**Pull request by Julien-Elie**
Also rewrap a long line, and remove a stray comment line in krb5.m4.

### CODE REVIEW

**Comment by Julien-Elie** [comment]
Hmm, it seems I have not created properly the branch (missing rebase I think).  Only the first commit is useful (329be14a7c93a968de96d301670eefb670fed4f9).

**Comment by Julien-Elie** [comment]
Also, though not related to indentation and not doing any harm, I've noted in _init-ntoa.m4_ that the first two arguments of `AC_CACHE_CHECK` could be surrounded by `[` and `]`:
`AC_CACHE_CHECK(for working inet_ntoa, rra_cv_func_inet_ntoa_works, _..._)`

Feel free to add them if you prefer.

**Comment by rra** [comment]
This is great, thanks (and also thanks for all the other PRs)! Is there some tool available to do this now, or did you check it by hand?

**Comment by Julien-Elie** [comment]
I did not unfortunately find some tool to do this...
All checked and edited by hand!
(except of course for included C code, for which I manually ran clang-format, but it was for INN, not rra-c-util)

Note that I only reviewed the indentation of files rra-c-util shares with INN.

**Pull request merged**
